apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db.chcaw88ym4qj.eu-west-2.rds.amazonaws.com:3306/resturantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db.chcaw88ym4qj.eu-west-2.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db.chcaw88ym4qj.eu-west-2.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:Nm0934406294@atlas-cluster.077c8.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka


  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  